facebook:
  client:
    clientId: 2627866720863471
    clientSecret: 
    accessTokenUri: 
    userAuthorizationUri: https://www.facebook.com/dialog/oauth?display=popup
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
    scope: email
  resource:
    userInfoUri: https://graph.facebook.com/me?fields=id,name,email,link

google:
  client:
    clientId: 
    clientSecret: 
    accessTokenUri: https://accounts.google.com/o/oauth2/token
    userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
    scope: email, profile
  resource:
    userInfoUri: https://www.googleapis.com/oauth2/v2/userInfo

kakao:
  client:
    clientId: 
    accessTokenUri: https://kauth.kakao.com/oauth2/token
    userAuthorizationUri: https://kauth.kakao.com/oauth2/authorize
  resource:
    userInfoUri: https://kapi.kakako.com/v1/user/me
